name: Publish

on:
  push:
    branches:
      - test

jobs:
  setup:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Install Node and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Check if version changed
        uses: EndBug/version-check@v2

  publish:
    needs: setup
    if: needs.setup.steps.check.outputs.changed == 'true'
    steps:
      - name: Install node modules
        if: steps.check.outputs.changed == 'true'
        run: |
          npm ci

      # - name: Build
      #   if: steps.check.outputs.changed == 'true'
      #   run: |
      #     npm run postinstall
      #     npm run build

      # - name: Publish release (macOS)
      #   if: startsWith(matrix.os, 'macos')
      #   env:
      #     CSC_IDENTITY_AUTO_DISCOVERY: ${{ secrets.CSC_IDENTITY_AUTO_DISCOVERY }}
      #     # This is used for uploading release assets to github
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     npm exec electron-builder -- --publish always --mac

      # - name: Publish release (Windows)
      #   if: startsWith(matrix.os, 'windows')
      #   env:
      #     # This is used for uploading release assets to github
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     npm exec electron-builder -- --publish always --win
