name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install Node, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install vips (macOS)
        run: brew install vips
        if: startsWith(matrix.os, 'macos')

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn install --prefer-offline --frozen-lockfile

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Publish release (macOS)
        if: startsWith(matrix.os, 'macos')
        env:
          # These values are used for auto updates signing
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn postinstall && yarn build && yarn electron-builder --publish always --mac -c.mac.identity=null

      - name: Publish release (Windows)
        if: startsWith(matrix.os, 'windows')
        env:
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn postinstall && yarn build && yarn electron-builder --publish always --win
