name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install node modules
        run: |
          npm ci
          npm audit signatures

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run package

      - name: Run tests
        run: |
          npm run lint
          npm exec tsc
          npm test
