name: Test

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install vips (Linux)
        run: |
          sudo apt-add-repository "deb http://azure.archive.ubuntu.com/ubuntu/ hirsute main universe"
          sudo apt-get update
          sudo cat /etc/apt/sources.list
          sudo apt-get install libvips libvips-dev=8.10.5-2ubuntu1 libglib2.0=2.68.0-1
        if: startsWith(matrix.os, 'ubuntu')
      - name: Install vips (macOS)
        run: brew install vips
        if: startsWith(matrix.os, 'macos')

      - name: yarn install
        run: |
          yarn install --frozen-lockfile --network-timeout 300000

      - name: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package
          yarn lint
          yarn tsc
          yarn test
