name: Test

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install vips (Linux)
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq libvips libvips-dev=8.10.5
        if: startsWith(matrix.os, 'ubuntu')
      - name: Install vips (macOS)
        run: brew install vips
        if: startsWith(matrix.os, 'macos')

      - name: yarn install
        run: |
          yarn install --frozen-lockfile --network-timeout 300000

      - name: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package
          yarn lint
          yarn tsc
          yarn test
