name: Test

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install vips (Linux)
        run: sudo apt-get install libvips libvips-dev
        if: startsWith(matrix.os, 'ubuntu')
      - name: Install vips (macOS)
        run: brew install vips
        if: startsWith(matrix.os, 'macos')

      - name: Test deps
        run: sudo find /usr -name glib-object.h
        if: startsWith(matrix.os, 'ubuntu')

      - name: Test deps 2
        run: pkg-config --cflags vips-cpp
        if: startsWith(matrix.os, 'ubuntu')

      - name: yarn install
        run: |
          yarn install --frozen-lockfile --network-timeout 300000

      - name: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package
          yarn lint
          yarn tsc
          yarn test
